config/routes.rb
Rails.application.routes.draw do
  resources :mining_types

  get '/welcome', to: "welcome#index"

  resources :coins

  get "up" => "rails/health#show", as: :rails_health_check


   root "coins#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/coin.rb
class Coin < ApplicationRecord
  belongs_to :mining_type #optional:true
end

app/models/mining_type.rb
class MiningType < ApplicationRecord
  has_many :coins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #before_action :set_locale

  #def set_locale
   # if params[:locale]
    #   cookies[:locale] = params[:locale]
    #end

    #if cookies[:locale]
      #if I18n.locale != cookies[:locale]
       # I18n.locale = cookies[:locale]
     # end
    end
 # end
#end

app/controllers/coins_controller.rb
class CoinsController < ApplicationController
  before_action :set_coin, only: %i[ show edit update destroy ]
  before_action :set_mining_type_options, only: [:new, :create, :update, :edit]


  # GET /coins or /coins.json
  def index
    @coins = Coin.all
  end

  # GET /coins/1 or /coins/1.json
  def show
  end

  # GET /coins/new
  def new
    @coin = Coin.new
  end

  # GET /coins/1/edit
  def edit
  end

  # POST /coins or /coins.json
  def create
    @coin = Coin.new(coin_params)

    respond_to do |format|
      if @coin.save
        format.html { redirect_to coin_url(@coin), notice: "Coin was successfully created." }
        format.json { render :show, status: :created, location: @coin }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @coin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /coins/1 or /coins/1.json
  def update
    respond_to do |format|
      if @coin.update(coin_params)
        format.html { redirect_to coin_url(@coin), notice: "Coin was successfully updated." }
        format.json { render :show, status: :ok, location: @coin }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @coin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /coins/1 or /coins/1.json
  def destroy
    @coin.destroy!

    respond_to do |format|
      format.html { redirect_to coins_url, notice: "Coin was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
def set_mining_type_options
  @mining_type_options =  MiningType.all.pluck(:description, :id)
end

    def set_coin
      @coin = Coin.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def coin_params
      params.require(:coin).permit(:description, :acronym, :url_image, :mining_type_id)
    end
end

app/controllers/mining_types_controller.rb
class MiningTypesController < ApplicationController
  before_action :set_mining_type, only: %i[ show edit update destroy ]

  # GET /mining_types or /mining_types.json
  def index
    @mining_types = MiningType.all
  end

  # GET /mining_types/1 or /mining_types/1.json
  def show
  end

  # GET /mining_types/new
  def new
    @mining_type = MiningType.new
  end

  # GET /mining_types/1/edit
  def edit
  end

  # POST /mining_types or /mining_types.json
  def create
    @mining_type = MiningType.new(mining_type_params)

    respond_to do |format|
      if @mining_type.save
        format.html { redirect_to mining_type_url(@mining_type), notice: "Mining type was successfully created." }
        format.json { render :show, status: :created, location: @mining_type }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @mining_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mining_types/1 or /mining_types/1.json
  def update
    respond_to do |format|
      if @mining_type.update(mining_type_params)
        format.html { redirect_to mining_type_url(@mining_type), notice: "Mining type was successfully updated." }
        format.json { render :show, status: :ok, location: @mining_type }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @mining_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mining_types/1 or /mining_types/1.json
  def destroy
    @mining_type.destroy!

    respond_to do |format|
      format.html { redirect_to mining_types_url, notice: "Mining type was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mining_type
      @mining_type = MiningType.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def mining_type_params
      params.require(:mining_type).permit(:description, :acronym)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    cookies[:curso] = "Curso de Ruby on Rails - Jackson Pires - cookies"
    session[:curso] = "Curso de Ruby on Rails - Jackson Pires - session"
    @meu_nome = params[:nome]
    @meu_curso = params[:curso]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def language
      if I18n.locale == :en
        "Estados Unidos"
      else
        "Português do brazil"
      end
    end
  def date_br
    Date.today.strftime("%d/%m/%Y")
  end

  def app_name
    "Crypton Wallet"
  end

  def ambiente_desenvolvimento
    if Rails.env.development?
      "desenvolvimento"
    else Rails.env.production?
      "produção"
    end
  end

end

app/helpers/coins_helper.rb
module CoinsHelper
end

app/helpers/mining_types_helper.rb
module MiningTypesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/coins/_coin.html.erb
<div id="<%= dom_id coin %>">
  <p>
    <strong><%=@coins.human_attribute_name(:description)%>:</strong>
    <%= coin.description %>
  </p>

  <p>
    <strong><%=@coins.human_attribute_name(:acronym)%></strong>
    <%= coin.acronym %>
  </p>

  <p>
    <strong><%=@coins.human_attribute_name(:url_image)%>:</strong>
    <%=image_tag coin.url_image, size:'35x35'%>
  </p>
</div>

app/views/coins/_form.html.erb
<%= form_with(model: coin) do |form| %>
  <% if coin.errors.any? %> 
    <div style="color: red">
      <h2><%= pluralize(coin.errors.count, "error") %> prohibited this coin from being saved:</h2>

      <ul>
        <% coin.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :acronym, style: "display: block" %>
    <%= form.text_field :acronym %>
  </div>

  <div>
    <%= form.label :url_image, style: "display: block" %>
    <%= form.text_field :url_image %>
  </div>

   <div>
    <%=form.label :mining_type_id%>
    <%=form.select("mining_type_id", @mining_type_options, {include_blank: "Selecione..." } )%>
    </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/coins/edit.html.erb
<h1>Editing coin</h1>

<%= render "form", coin: @coin %>

<br>

<div>
  <%= link_to "Show this coin", @coin %> |
  <%= link_to "Back to coins", coins_path %>
</div>

app/views/coins/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Coins</h1>

<div id="coins">
  <% @coins.each do |coin| %>
    <%= render coin %>
    <p>
      <%= link_to t("links.show"), coin , class:"btn btn-primary" %>
    </p>
  <% end %>
</div>

<%= link_to t("links.new_coin"), new_coin_path, class:"btn btn-primary" %>

app/views/coins/new.html.erb
<h1>New coin</h1>

<%= render "form", coin: @coin %>

<br>

<div>
  <%= link_to "Back to coins", coins_path %>
</div>

app/views/coins/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @coin %>

<div>
  <%= link_to "Edit this coin", edit_coin_path(@coin) %> |
  <%= link_to "Back to coins", coins_path %>

  <%= button_to "Destroy this coin", @coin, method: :delete %>
</div>

app/views/layouts/adm.html.erb
<h1>LAYOUT ADM TESTE </h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CryptoWallet</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </head>

  <body>
     <div class="container-fluid">
              <ul class="nav justify-content-end">
            
            <li class="nav-item">
              <%=link_to 'Português', '/welcome/?locale=pt-BR', class:"nav-link"%>
            </li>
            <li class="nav-item">
          <%=link_to 'inglês', '/welcome/?locale=en', class:"nav-link"%>
            </li>
 
            </ul>
 <%= yield %>
</body>
     </div>
</html>

app/views/mining_types/_form.html.erb
<%= form_with(model: mining_type) do |form| %>
  <% if mining_type.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(mining_type.errors.count, "error") %> prohibited this mining_type from being saved:</h2>

      <ul>
        <% mining_type.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :acronym, style: "display: block" %>
    <%= form.text_field :acronym %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/mining_types/_mining_type.html.erb
<div id="<%= dom_id mining_type %>">
  <p>
    <strong><%=@mining_types.human_attribute_name(:description)%>:</strong>
    <%= mining_type.description %>
  </p>

  <p>
    <strong><%=@mining_types.human_attribute_name(:acronym)%>:</strong>
    <%= mining_type.acronym %>
  </p>

</div>

app/views/mining_types/edit.html.erb
<h1>Editing mining type</h1>

<%= render "form", mining_type: @mining_type %>

<br>

<div>
  <%= link_to "Show this mining type", @mining_type %> |
  <%= link_to "Back to mining types", mining_types_path %>
</div>

app/views/mining_types/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Mining types</h1>

<div id="mining_types">
  <% @mining_types.each do |mining_type| %>
    <%= render mining_type %>
    <p>
      <%= link_to t("links.show"), mining_type, class:"btn btn-primary" %>
    </p>
  <% end %>
</div>

<%= link_to t("links.new_mining_type"), new_mining_type_path, class:"btn btn-primary" %>

app/views/mining_types/new.html.erb
<h1>New mining type</h1>

<%= render "form", mining_type: @mining_type %>

<br>

<div>
  <%= link_to "Back to mining types", mining_types_path %>
</div>

app/views/mining_types/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @mining_type %>

<div>
  <%= link_to "Edit this mining type", edit_mining_type_path(@mining_type) %> |
  <%= link_to "Back to mining types", mining_types_path %>

  <%= button_to "Destroy this mining type", @mining_type, method: :delete %>
</div>

app/views/welcome/_menu.html.erb
<ul>
    
    <%=link_to "Criar nova moeda", root_path, class:"btn btn-primary btn-lg", role:"button" %>
      <%=link_to "Moedas", root_path, class:"btn btn-primary btn-lg", role:"button"%>
    <%=link_to "Tipo de mineração", mining_types_path,class:"btn btn-primary btn-lg", role:"button"%>
</ul>

app/views/welcome/index.html.erb
<div class="jumbotron">
  <h1 class="display-4"><%= t('welcome')%></h1>
  <p class="lead"><%=t('lead')%></p>
  <hr class="my-4">
  <p><%=t('options')%></p>
  <%=link_to t('new coin'), new_coin_path, class:"btn btn-primary btn-lg", role:"button" %>
      <%=link_to t('coins'), root_path, class:"btn btn-primary btn-lg", role:"button"%>
    <%=link_to  t('mining_type'), mining_types_path,class:"btn btn-primary btn-lg", role:"button"%>
</div>


<p>A linguá utilizada é o:<strong><%=t('actual_locale')%></strong></p> 
<p><strong>Data:</strong> <%=l(Date.today)%></p>

<%=I18n.t('hello')%>

<strong>
    <p><%=app_name%></p>
</strong>

<p>A soma é: <%=1+1%></p>

<p>Seu nome de trás para a frente é: <%= "Italo".reverse%></p>

<%a= "Primeira variável"%>
<p>Imprimindo variável a: <strong><%= a%></strong></p>

<p>Data de hoje <%=Date.today%></p>


 
<p>Você esta em ambiente de<strong> <%= ambiente_desenvolvimento%></strong></p>

<p>Eu sou uma variável de instância/sessão <strong><%= @meu_nome%></strong></p>

<p>Curso de<strong> <%=@meu_curso%></strong></p>